import type { AchievementItem, ExperienceItem, TechSkill, VideoItem } from "@/types";

export const EXPERIENCE: ExperienceItem[] = [
  {
    id: "exp-1",
    role: "[Insert Job Title — e.g., Senior Game Tools Engineer]",
    company: "[Insert Company Name]",
    period: "[Month YYYY] — [Month YYYY / Present]",
    location: "[City, Country / Remote]",
    type: "[Full-time / Contract / Freelance]",
    outcomes: [
      "[Insert Outcome 1 — e.g., Architected a custom asset pipeline that reduced build times by X%]",
      "[Insert Outcome 2 — e.g., Owned and shipped [Feature Name] used by N engineers across M projects]",
      "[Insert Outcome 3 — e.g., Led technical design review for [System Name], reducing runtime overhead by X ms]",
      "[Insert Outcome 4 — scalability, optimization, or ownership focus]",
    ],
    techStack: ["[Tech 1]", "[Tech 2]", "[Tech 3]"],
    highlight: "[Insert High-Impact Metric — e.g., 40% reduction in iteration time]",
  },
  {
    id: "exp-2",
    role: "[Insert Job Title]",
    company: "[Insert Company Name]",
    period: "[Month YYYY] — [Month YYYY]",
    location: "[City, Country / Remote]",
    type: "[Full-time / Contract]",
    outcomes: ["[Insert Outcome 1]", "[Insert Outcome 2]", "[Insert Outcome 3]"],
    techStack: ["[Tech 1]", "[Tech 2]"],
    highlight: "[Insert High-Impact Metric for CPU/GPU Optimization]",
  },
  {
    id: "exp-3",
    role: "[Insert Job Title]",
    company: "[Insert Company Name]",
    period: "[Month YYYY] — [Month YYYY]",
    location: "[City, Country]",
    type: "[Internship / Contract]",
    outcomes: ["[Insert Outcome 1]", "[Insert Outcome 2]"],
    techStack: ["[Tech 1]", "[Tech 2]"],
    highlight: "[Insert Architecture or Scalability Achievement]",
  },
];

export const MECHANICS_VIDEOS: VideoItem[] = [
  {
    id: "vid-1",
    title: "[Insert System/Mechanic Name — e.g., Procedural Terrain Generator]",
    description:
      "[Insert 1–2 sentence strategic description of the system, its architecture, and engineering challenge solved]",
    techStack: ["Unity", "C#", "[Insert Additional Tech]"],
    videoSrc: "/videos/[filename-1].mp4",
    thumbnailSrc: "/thumbnails/[filename-1].jpg",
    category: "[Insert Category — e.g., Engine Tools / Gameplay Systems / Rendering]",
  },
  {
    id: "vid-2",
    title: "[Insert System/Mechanic Name]",
    description: "[Insert strategic description]",
    techStack: ["Unreal Engine 5", "C++", "[Insert Additional Tech]"],
    videoSrc: "/videos/[filename-2].mp4",
    thumbnailSrc: "/thumbnails/[filename-2].jpg",
    category: "[Insert Category]",
  },
  {
    id: "vid-3",
    title: "[Insert System/Mechanic Name]",
    description: "[Insert strategic description]",
    techStack: ["Unity", "C#", "Shader Graph"],
    videoSrc: "/videos/[filename-3].mp4",
    thumbnailSrc: "/thumbnails/[filename-3].jpg",
    category: "[Insert Category]",
  },
  {
    id: "vid-4",
    title: "[Insert System/Mechanic Name]",
    description: "[Insert strategic description]",
    techStack: ["[Engine]", "[Language]"],
    videoSrc: "/videos/[filename-4].mp4",
    thumbnailSrc: "/thumbnails/[filename-4].jpg",
    category: "[Insert Category]",
  },
  {
    id: "vid-5",
    title: "[Insert System/Mechanic Name]",
    description: "[Insert strategic description]",
    techStack: ["[Engine]", "[Language]"],
    videoSrc: "/videos/[filename-5].mp4",
    thumbnailSrc: "/thumbnails/[filename-5].jpg",
    category: "[Insert Category]",
  },
  {
    id: "vid-6",
    title: "[Insert System/Mechanic Name]",
    description: "[Insert strategic description]",
    techStack: ["[Engine]", "[Language]"],
    videoSrc: "/videos/[filename-6].mp4",
    thumbnailSrc: "/thumbnails/[filename-6].jpg",
    category: "[Insert Category]",
  },
  {
    id: "vid-7",
    title: "[Insert System/Mechanic Name]",
    description: "[Insert strategic description]",
    techStack: ["[Engine]", "[Language]"],
    videoSrc: "/videos/[filename-7].mp4",
    thumbnailSrc: "/thumbnails/[filename-7].jpg",
    category: "[Insert Category]",
  },
  {
    id: "vid-8",
    title: "[Insert System/Mechanic Name]",
    description: "[Insert strategic description]",
    techStack: ["[Engine]", "[Language]"],
    videoSrc: "/videos/[filename-8].mp4",
    thumbnailSrc: "/thumbnails/[filename-8].jpg",
    category: "[Insert Category]",
  },
];

export const ACHIEVEMENTS: AchievementItem[] = [
  {
    id: "ach-fyp",
    label: "1st Prize",
    title: "FYP Exhibition",
    subtitle: "[Insert Full Project Title]",
    description:
      "[Insert 1–2 sentence description of what the project achieved, the problem it solved, and why it won]",
    pdfLink: "[Insert Certificate PDF Link — /certificates/fyp-award.pdf]",
    category: "Award",
    icon: "trophy",
    size: "large",
  },
  {
    id: "ach-cr",
    label: "Class Representative",
    title: "University Leadership",
    subtitle: "[Insert Batch / Cohort — e.g., BSCS 2021–2025]",
    description:
      "[Insert 1-sentence description of scope — number of peers represented, initiatives led]",
    pdfLink: null,
    category: "Leadership",
    icon: "users",
    size: "medium",
  },
  {
    id: "ach-tour",
    label: "Tour Organizer",
    title: "University Leadership",
    subtitle: "[Insert Event/Tour Name and Year]",
    description:
      "[Insert 1-sentence description — number of participants, logistics managed, outcome]",
    pdfLink: null,
    category: "Leadership",
    icon: "map",
    size: "medium",
  },
  {
    id: "ach-football",
    label: "Captain",
    title: "Football Team",
    subtitle: "[Insert Team Name / Tournament / Year]",
    description:
      "[Insert 1-sentence description — team size, season record, or notable achievement]",
    pdfLink: null,
    category: "Sports",
    icon: "shield",
    size: "medium",
  },
  {
    id: "ach-ieee",
    label: "Appreciation",
    title: "IEEE RAS",
    subtitle: "[Insert Chapter Name and Year]",
    description: "[Insert reason for appreciation — contribution, role, or project]",
    pdfLink: "[Insert Certificate PDF Link — /certificates/ieee-ras.pdf]",
    category: "Society",
    icon: "award",
    size: "small",
  },
  {
    id: "ach-gdsc",
    label: "Appreciation",
    title: "GDSC",
    subtitle: "[Insert Chapter Name and Year]",
    description: "[Insert reason for appreciation — contribution, role, or project]",
    pdfLink: "[Insert Certificate PDF Link — /certificates/gdsc.pdf]",
    category: "Society",
    icon: "award",
    size: "small",
  },
];

export const TECH_ARSENAL: Record<string, TechSkill[]> = {
  "Game Engines": [
    { name: "Unity", proficiency: "[Expert / Advanced / Proficient]" },
    { name: "Unreal Engine 5", proficiency: "[Expert / Advanced / Proficient]" },
    { name: "[Insert Additional Engine]", proficiency: "[Proficiency Level]" },
  ],
  Languages: [
    { name: "C#", proficiency: "[Expert / Advanced]" },
    { name: "C++", proficiency: "[Advanced / Proficient]" },
    { name: "TypeScript", proficiency: "[Advanced / Proficient]" },
    { name: "[Insert Language]", proficiency: "[Proficiency Level]" },
  ],
  "Web & Mobile": [
    { name: "Next.js", proficiency: "[Advanced / Proficient]" },
    { name: "React", proficiency: "[Advanced / Proficient]" },
    { name: "[Insert Framework]", proficiency: "[Proficiency Level]" },
  ],
  "Architecture Patterns": [
    { name: "[Insert Pattern — e.g., ECS / DOTS]", proficiency: "[Advanced]" },
    { name: "[Insert Pattern — e.g., Service Locator]", proficiency: "[Advanced]" },
    {
      name: "[Insert Pattern — e.g., State Machine Architecture]",
      proficiency: "[Advanced]",
    },
  ],
  "QA & DevOps": [
    { name: "[Insert Tool — e.g., Jenkins / GitHub Actions]", proficiency: "[Proficient]" },
    { name: "[Insert Tool — e.g., Unity Test Framework]", proficiency: "[Proficient]" },
    { name: "[Insert Tool]", proficiency: "[Proficient]" },
  ],
};
